@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

'==============================
' Core model relationships
'==============================
AddressBook *-down-> "1" UniquePersonList
AddressBook *-down-> "1" UniqueProjectList

Class "{abstract}\nPerson" as Person

UniquePersonList -down-> "*" Person
UniqueProjectList -down-> "*" Project

Person -down-> "*" Remark

Person *--> "1" Name
Person *--> "1" Email
Person --> "0..1" Phone
Person --> "0..1" Telegram
Person --> "1" Role
Person --> "0..*" Project
Project --> "0..*" Person


Project *--> "1" ProjectName
Project --> "0..1" Description
Project --> "1" LastUpdate

@enduml
