@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "ProjectBook Storage" #F4F6F6{
Class "<<interface>>\nProjectBookStorage" as ProjectBookStorage
Class JsonProjectBookStorage
Class JsonSerializableProjectBook
Class JsonAdaptedPerson
Class JsonAdaptedProject
Class JsonAdaptedRemark
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ProjectBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ProjectBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonProjectBookStorage .up.|> ProjectBookStorage
JsonProjectBookStorage ..> JsonSerializableProjectBook
JsonSerializableProjectBook --> "*" JsonAdaptedPerson
JsonSerializableProjectBook --> "*" JsonAdaptedProject
JsonAdaptedPerson --> "*" JsonAdaptedRemark

@enduml
